import type { Metadata } from "next";

import "./globals.css";
import { libre_baskerville } from "./fonts";
import { Navbar } from "@/components/Navbar";
import { Footer } from "@/components/Footer";

export const metadata: Metadata = {
  title: `Mats and Margarita's Wedding Website`,
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${libre_baskerville.className} bg-blue-200`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
